"""update models

Revision ID: 992cbd7a2252
Revises: 82eff4b91907
Create Date: 2025-09-01 18:15:27.446852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '992cbd7a2252'
down_revision: Union[str, Sequence[str], None] = '82eff4b91907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repair_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'MESSAGE', 'COMPLETED', 'CANCELLED', name='requeststatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['repair_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_messages_id'), 'admin_messages', ['id'], unique=False)
    op.create_table('service_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pay', sa.String(length=50), nullable=False),
    sa.Column('parts_used', sa.Text(), nullable=True),
    sa.Column('warranty_info', sa.Text(), nullable=False),
    sa.Column('data_completed', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['repair_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_records')
    op.drop_index(op.f('ix_admin_messages_id'), table_name='admin_messages')
    op.drop_table('admin_messages')
    op.drop_table('repair_requests')
    # ### end Alembic commands ###
